apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command: ["echo", "Hello I'm running job"]
      restartPolicy: Never
  backoffLimit: 1
