apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env-secrets
spec:
  containers:
    - name: my-container
      image: busybox
      env:
        - name: MY_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: USERNAME
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: PASSWORD
      command: ["/bin/sh", "-c", "echo Username: $MY_USERNAME; echo Password: $MY_PASSWORD; sleep 3600"]
