apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume-secret
spec:
  containers:
    - name: my-container
      image: busybox
      volumeMounts:
        - name: secret-volume
          mountPath: "/mnt/secret"
      command: ["/bin/sh", "-c", "echo volumeName: $secret-volume; sleep 3600"]
  volumes:
    - name: secret-volume
      secret:
        secretName: my-volume-secret
