# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-liveness-pod
# spec:
#   containers:
#     - name: nginx-container
#       image: nginx
#       livenessProbe:
#         exec:
#           command:
#             - ls 
#         initialDelaySeconds: 0
#         periodSeconds: 5


apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      livenessProbe:
        exec:
          command:
            - ls
        initialDelaySeconds: 5
        periodSeconds: 5
      startupProbe:
        exec:
          command:
            - ls
        initialDelaySeconds: 5
        periodSeconds: 5


