apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - name: web  # Container name
          image: techno12/abhi-notejam-psql
          env:
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: DB_HOST
              value: db-service
            - name: DB_NAME
              value: notejam
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
          ports:
            - containerPort: 8000
      restartPolicy: Always
