
apiVersion: v1
kind: Service

metadata:
  labels:
    name: web-service
  name: web-service
spec:
  type: NodePort
  ports:
    - name: "http"
      protocol: TCP
      port: 8000  
      targetPort: 8000 
  selector:
    name: web
