apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default  
  name: pod-log-reader-rolebinding
subjects:
  - kind: User
    name: asliabhi12
roleRef:
  kind: Role
  name: pod-log-reader-role
  apiGroup: rbac.authorization.k8s.io
