apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default 
  name: pod-log-reader-role
rules:
  - apiGroups: [""]
    resources: ["pods/log", "pods"]
    verbs: ["get", "watch", "list"]
