apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.8-apache
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /readme.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readme.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
  strategy:
    type: Recreate
