apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  containers:
    - name: nginx-container
      image: nginx
  initContainers:
    - name: busybox-init-container
      image: busybox
      command: ["sh", "-c", "sleep 20"]
