apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: container1
      image: nginx
    - name: container2
      image: busybox
      command: ["sh", "-c", "echo Hello from container2; sleep 3600"]
    - name: container3
      image: alpine
      command: ["sh", "-c", "echo Hello from container3; sleep 3600"]
